# List of dependencies (TBD) to create a conda environment.
name: musicologist
channels:
  - conda-forge
dependencies:
  - python==3.11
  - numpy==2.2.4
  - pandas==2.2.3
  - matplotlib==3.10.1
  - pip
  - pip:
    - torch==2.6.0
    - torchaudio==2.6.0
    - torch_xla==2.6.0
    - diffusers==0.32.3
    - muq
    - librosa
    - laion-clap
    - clamp3
    - transformers
    - jukemirlib
    - tdqm
    - soundfile