---
embed_model: 'laion-clap'
concepts:
- 'is_blown'
- 'is_string'
class_models:
- 'logistic'
overwrite: False
hparams:
- test_size: 0.2
truncation_ts:
- 5
- 10
- 15
- 20
- 25
- 30
- 35
- 40
- 45
- 49