---
embed_model: 'laion-clap'
concepts:
- 'is_staccato'
class_models:
- 'logistic'
overwrite: False
hparams:
- num_layers: 4
- hidden_dim: 512
- input_dim: 512
- output_dim: 1
- test_size: 0.2
- svm_kernel: "rbf"
- svm_C: 1.0
- epochs: 100
- lr: 1e-3
- batch_size: 32
truncation_ts:
- 5
- 10
- 15
- 20
- 25
- 30
- 35
- 40
- 45
- 49