---
model_name: "stable-diffusion"

batch_size: 10
num_batches: 1

prompt_path: 'data/prompts/prompt_test.txt'
output_dir: 'data/generated'

steps: 10
sample_length: 10
early_stopping: True
truncation_ts:
- 3
- 6
- 9
# - 12
# - 15
# - 18
# - 21
# - 24
# - 27
# - 30
# - 33
# - 36
# - 39
# - 42
# - 45
# - 48
verbose: true
