---
model_name: "stable-diffusion"

batch_size: 4
num_batches: 1

prompt_path: 'data/prompt.txt'
output_dir: 'data/audio'

steps:
  - 50
sample_length: 30
early_stopping: True
truncation_t: 45
verbose: true
