---
model_name: "stable-diffusion"

prompt_path: 'data/prompts/prompt.txt'
output_dir: 'data/generated'

batch_size: 7
num_batches: 1


steps: 50
sample_length: 10
early_stopping: True
truncation_ts:
- 5
- 10
- 15
- 20
- 25
- 30
- 35
- 40
- 45
- 49
verbose: true
