---
model_name: "stable-diffusion"

batch_size: 1
num_batches: 1

prompt_path: 'data/prompt_test.txt'
output_dir: 'data/perturbation'

steps: 50
sample_length: 30
experiment_type: "perturbation"
truncation_ts:
 - 49
perturbation_ts:
 - 2
 - 25
n_perturbations: 3
verbose: true
