---
model_name: "stable-diffusion"

batch_size: 1
num_batches: 1

prompt_path: 'data/prompt_test.txt'
output_dir: 'data/generated'

steps: 100
sample_length: 30
early_stopping: True
truncation_ts:
 - 49
verbose: true
